name: Publish libChart

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  publish-libchart:
    name: Publish libChart to GHCR
    uses: orhayoun-eevee/build-workflow/.github/workflows/release-chart.yaml@bf26f6189979fff20a41b775faf9a23f1058e27c
    with:
      chart_path: libChart
    secrets: inherit
