name: Publish libChart

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  publish-libchart:
    name: Publish libChart to GHCR
    uses: orhayoun-eevee/build-workflow/.github/workflows/release-chart.yaml@71d49e5a28934003a8ae8e764b9988b53726638b
    with:
      chart_path: libChart
    secrets: inherit
