name: Publish libChart

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write
  id-token: write

concurrency:
  group: on-tag-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-libchart:
    name: Publish libChart to GHCR
    uses: orhayoun-eevee/build-workflow/.github/workflows/release-chart.yaml@v0.1.13
    with:
      chart_path: libChart
      release_environment: production
      enable_signing: true
