name: Publish libChart

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  publish-libchart:
    name: Publish libChart to GHCR
    uses: orhayoun-eevee/build-workflow/.github/workflows/release-chart.yaml@2c8d867912a2c7590cee174f0b8954c8f527583c
    with:
      chart_path: libChart
    secrets: inherit
